### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by agungsugiarto** [iniakunhuda/api-cookpad#1]
Saya mendapatkan pesan seperti ini : 
Fatal error: Uncaught exception 'PHPHtmlParser\Exceptions\EmptyCollectionException' with message 'The collection does not contain any Nodes.' in C:\xampp\htdocs\api-cookpad\vendor\paquettg\php-html-parser\src\PHPHtmlParser\Dom\Collection.php:58 Stack trace: #0 C:\xampp\htdocs\api-cookpad\cookpad\Cookpad.php(497): PHPHtmlParser\Dom\Collection->__get('text') #1 C:\xampp\htdocs\api-cookpad\index.php(10): Cookpad->search('kukus surabaya') #2 {main} thrown in C:\xampp\htdocs\api-cookpad\vendor\paquettg\php-html-parser\src\PHPHtmlParser\Dom\Collection.php on line 58
![error](https://user-images.githubusercontent.com/10989147/37875599-060e3288-306c-11e8-8557-65d07de22e7c.png)

**Comment by Marlendo** [comment]
sama saya juga ... cara mengatasinya gimana gan ???? uda ketemu???

**Comment by iniakunhuda** [comment]
Hallo! Silahkan dicek kembali ya, sudah saya perbaiki. @Marlendo @agungsugiarto  Thanks :smile:

**Comment by muazinasro** [comment]
saya juga mengalami hal yang sama. Kenapa ya?
