### ISSUE TITLE
Rekomendasi API

### ISSUE THREAD

**Issue by sulaimangari** [iniakunhuda/api-cookpad#4]
ada rekomendasi API yang masih bisa digunakan bang?

**Comment by gensart-x** [comment]
@sulaimangari kebetulan saya lg buat bang, nnti tak kabari lg disini.

**Comment by gensart-x** [comment]
https://kyoanna.insomnia247.nl

**Comment by sulaimangari** [comment]
GG beneran dibikin bang, kirain dah lupa. Fellow Bokuyaba enjoyer ternyata wkwkw. Thanks alot ya.
